-   id: code_snippet_to_md
    name: Code Snippet to Markdown
    description: Keeps code snippets in Markdown files in sync with source code files.
    entry: code_snippet_to_md
    pass_filenames: false
    language: python
    types_or: [markdown, python, c, c++, java, rust]
    args: [--input=README.md]
